# Stage 1: Build the Vue application
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm config set strict-ssl false && npm i -g @quasar/cli && npm ci --ignore-scripts
COPY . .
RUN npm run build # This command generates production-ready files in the 'dist' folder

# Stage 2: Serve the application with NGINX
FROM nginx:1.16-alpine
COPY --from=builder /app/dist/spa /usr/share/nginx/html
# Optional: Copy a custom NGINX configuration file if needed
COPY docker/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"] # Runs NGINX in the foreground so Docker keeps running
